export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/users/login'
export const REGISTRATION_ROUTE = '/users/registration'
export const MAIN_ROUTE = '/'
export const SUPERHEROES_ROUTE = '/superheroes'
export const FILMS_ROUTE = '/films'
export const POWERS_ROUTE = '/powers'
export const NO_MATCH_ROUTE = '*'